version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: francescoxx/nestapp:1.0.0
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - DB_USERNAME=nestjs
      - DB_PASSWORD=gg@24
      - DB_DATABASE=nestdb
      - DB_PORT=5432
      - DB_HOST=localhost
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: nestjs
      POSTGRES_PASSWORD: gg@24
      POSTGRES_DB: nestdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
